# Generated by Django 3.1.7 on 2021-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addphoto',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
