# Generated by Django 3.1.7 on 2021-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_app', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addphoto',
            name='delivery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
