# Generated by Django 3.1.7 on 2021-04-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography_app', '0004_addphoto_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addphoto',
            name='delivery',
        ),
    ]
