# Generated by Django 3.1.7 on 2021-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_app', '0005_remove_addphoto_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billstatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
